name: My panda ci
on: 
  push:
    branches: [main] # This will run everytime you push to the 'main' branch

jobs:
  builds:
      runs-on: ubuntu-latest
      name: my build
      steps:
        - name: Check out code
          uses: actions/checkout@v2 # This is actually a repo
        - name: Send a discord message
          uses: discord-actions/message@v2 # This is also a rep
          with: 
                # A Discord webhook URL
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
            # A message to send to Discord
            message: "HELLO!!!!!"
            username: "Pau Pau"
            avatar: "https://carbonmoves.com/wp-content/uploads/2021/11/Foodpanda-x-Taipei-101-1-1670x1670.png"
